version: '3.1'
services:
  postgres:
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: sample_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password